<?php
// aaaaa
function comment_redirect_form_alter(&$form, $form_state, $form_id) {
    if ($form_id == "comment_form"){

        unset($form['preview']);
        $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'), '#weight' => 20);
        $form['submission_path'] = array(
            '#type' => 'hidden',
            '#default_value' => $_GET['q'],
            '#weight' => -100,
        );
        // is this a new comment or a reply?
        $reply = $form['#parameters'][3] == "Reply";
        $parent_comment = $form['#parameters'][2]['pid']; // no parent in case of new comment
        if ($parent_comment){
            $form['#redirect'] = array("node/" . $form['#parameters'][2]['nid'],"",'comment-' . $form['#parameters'][2]['pid']);
        }else{
            $form['#redirect'] = array($form['#parameters'][1]['post']['submission_path'],"",'comments');
        }
        
    }
    $var = $form['#parameters'][3];
}

?>
