<?php
// $Id$

/*
 *
 * Get the path from the webserver root and strip out the index.php or
 * whatever.php to get the path in the format of /group/groupname/cgi-bin/drupal
 *
 *
 */

$su_rewritebase = $_SERVER['SCRIPT_NAME'];
$su_rewritebase = preg_replace('/\/\w*\.php$/', '', $su_rewritebase);

/*
 *
 * Uncomment the following and put in your RewriteBase path
 * if the code above is not working
 *
 */

//$su_rewritebase = "/group/groupname/cgi-bin/drupal"; //NO trailing slash

/*
 *
 * Build the regex pattern and then strip /group/groupname/cgi-bin/drupal
 * from the $_SERVER['REQUEST_URI'] variable
 *
 *
 */
if (!empty($_SERVER['HTTP_X_FORWARDED_HOST'])) {
  $pattern = preg_replace('/\//', '\/', $su_rewritebase);
  $_SERVER['REQUEST_URI'] = preg_replace("/$pattern/", '', $_SERVER['REQUEST_URI']);
}